service: lambda-perf
provider:
  name: aws
  tracing:
    lambda: true

package:
  individually: true
  exclude:
    - ./go/**
  include:
    - ./go/bin/**

# package:

plugins:
  - serverless-rust

functions:
  node:
    handler: node/index.main
    runtime: nodejs12.x
  node-ts:
    handler: node-ts/dist/index.main
    runtime: nodejs12.x
  go:
    handler: go/bin/main
    runtime: go1.x
  rust:
    handler: rust
    runtime: rust
    rust:
      # Because our serverless file is in a different directory than our rust project
      cargoFlags: "--manifest-path rust/Cargo.toml"
