service: lambda-perf-go
provider:
  name: aws
  tracing:
    lambda: true
  runtime: go1.x

# https://www.serverless.com/blog/framework-example-golang-lambda-support
package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  main:
    handler: bin/main
